package ejerciciosclases;

public class ArithmeticException extends Throwable {
    public static void main(String[] args) {
        int a= 10, b=0;
        try{
            System.out.println("El resultado es:"+ (a/b));// Divisi칩n por cero
        } catch (java.lang.ArithmeticException ex){
            System.out.println("Excepci칩n capturada: "+ex.getMessage());
        } finally{
            System.out.println("Se va a finalizar la operaci칩n matem치tica. \n");
        }
    }
}
